//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MortysDLP.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2026.01.05")]
        public string CurrentVersion {
            get {
                return ((string)(this["CurrentVersion"]));
            }
            set {
                this["CurrentVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DownloadPath {
            get {
                return ((string)(this["DownloadPath"]));
            }
            set {
                this["DownloadPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tools\\\\yt-dlp.exe")]
        public string YtdlpPath {
            get {
                return ((string)(this["YtdlpPath"]));
            }
            set {
                this["YtdlpPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tools\\\\ffmpeg.exe")]
        public string FfmpegPath {
            get {
                return ((string)(this["FfmpegPath"]));
            }
            set {
                this["FfmpegPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tools\\\\ffprobe.exe")]
        public string FfprobePath {
            get {
                return ((string)(this["FfprobePath"]));
            }
            set {
                this["FfprobePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TimespanFrom {
            get {
                return ((string)(this["TimespanFrom"]));
            }
            set {
                this["TimespanFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TimespanTo {
            get {
                return ((string)(this["TimespanTo"]));
            }
            set {
                this["TimespanTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckedFirstSeconds {
            get {
                return ((bool)(this["CheckedFirstSeconds"]));
            }
            set {
                this["CheckedFirstSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckedVideoFormat {
            get {
                return ((bool)(this["CheckedVideoFormat"]));
            }
            set {
                this["CheckedVideoFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckedAudioOnly {
            get {
                return ((bool)(this["CheckedAudioOnly"]));
            }
            set {
                this["CheckedAudioOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckedTimespan {
            get {
                return ((bool)(this["CheckedTimespan"]));
            }
            set {
                this["CheckedTimespan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FirstSecondsSeconds {
            get {
                return ((string)(this["FirstSecondsSeconds"]));
            }
            set {
                this["FirstSecondsSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SelectedAudioFormat {
            get {
                return ((string)(this["SelectedAudioFormat"]));
            }
            set {
                this["SelectedAudioFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest")]
        public string YtdlpReleaseURL {
            get {
                return ((string)(this["YtdlpReleaseURL"]));
            }
            set {
                this["YtdlpReleaseURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DownloadAudioOnlyPath {
            get {
                return ((string)(this["DownloadAudioOnlyPath"]));
            }
            set {
                this["DownloadAudioOnlyPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckedAudioOnlyPath {
            get {
                return ((bool)(this["CheckedAudioOnlyPath"]));
            }
            set {
                this["CheckedAudioOnlyPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MortysDLP-Updater.exe")]
        public string MortysDLPUpdateExeFile {
            get {
                return ((string)(this["MortysDLPUpdateExeFile"]));
            }
            set {
                this["MortysDLPUpdateExeFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MortysDLP.exe")]
        public string MortysDLPExeFile {
            get {
                return ((string)(this["MortysDLPExeFile"]));
            }
            set {
                this["MortysDLPExeFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MortysDLP_Update.zip")]
        public string MortysDLPUpdateZipFile {
            get {
                return ((string)(this["MortysDLPUpdateZipFile"]));
            }
            set {
                this["MortysDLPUpdateZipFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MortysDLP-Updater")]
        public string MortysDLPUpdaterFolderName {
            get {
                return ((string)(this["MortysDLPUpdaterFolderName"]));
            }
            set {
                this["MortysDLPUpdaterFolderName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Updater")]
        public string MortysDLPUpdaterBaseFolderName {
            get {
                return ((string)(this["MortysDLPUpdaterBaseFolderName"]));
            }
            set {
                this["MortysDLPUpdaterBaseFolderName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("latest")]
        public string VersionSkip {
            get {
                return ((string)(this["VersionSkip"]));
            }
            set {
                this["VersionSkip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ForceEnglishLanguage {
            get {
                return ((bool)(this["ForceEnglishLanguage"]));
            }
            set {
                this["ForceEnglishLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("download_history.json")]
        public string DownloadHistoryFileName {
            get {
                return ((string)(this["DownloadHistoryFileName"]));
            }
            set {
                this["DownloadHistoryFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public short DownloadHistoryFileMaxEntries {
            get {
                return ((short)(this["DownloadHistoryFileMaxEntries"]));
            }
            set {
                this["DownloadHistoryFileMaxEntries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.github.com/repos/MortysTerminal/MortysDLP/releases/latest")]
        public string MortysDLPGitHubAPIURL {
            get {
                return ((string)(this["MortysDLPGitHubAPIURL"]));
            }
            set {
                this["MortysDLPGitHubAPIURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://github.com/MortysTerminal/MortysDLP")]
        public string MortysDLPGitHubURL {
            get {
                return ((string)(this["MortysDLPGitHubURL"]));
            }
            set {
                this["MortysDLPGitHubURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Höchste")]
        public string SelectedVideoQuality {
            get {
                return ((string)(this["SelectedVideoQuality"]));
            }
            set {
                this["SelectedVideoQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mp4")]
        public string SelectedVideoFormat {
            get {
                return ((string)(this["SelectedVideoFormat"]));
            }
            set {
                this["SelectedVideoFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192k")]
        public string SelectedAudioBitrate {
            get {
                return ((string)(this["SelectedAudioBitrate"]));
            }
            set {
                this["SelectedAudioBitrate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckedCustomFilename {
            get {
                return ((bool)(this["CheckedCustomFilename"]));
            }
            set {
                this["CheckedCustomFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomFilename {
            get {
                return ((string)(this["CustomFilename"]));
            }
            set {
                this["CustomFilename"] = value;
            }
        }
    }
}
