//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MortysDLP.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("latest")]
        public string CURRENTVERSION {
            get {
                return ((string)(this["CURRENTVERSION"]));
            }
            set {
                this["CURRENTVERSION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DOWNLOADPATH {
            get {
                return ((string)(this["DOWNLOADPATH"]));
            }
            set {
                this["DOWNLOADPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tools\\\\yt-dlp.exe")]
        public string YTDLPPATH {
            get {
                return ((string)(this["YTDLPPATH"]));
            }
            set {
                this["YTDLPPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tools\\\\ffmpeg.exe")]
        public string FFMPEGPATH {
            get {
                return ((string)(this["FFMPEGPATH"]));
            }
            set {
                this["FFMPEGPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tools\\\\ffprobe.exe")]
        public string FFPROBEPATH {
            get {
                return ((string)(this["FFPROBEPATH"]));
            }
            set {
                this["FFPROBEPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ZEITSPANNE_VON {
            get {
                return ((string)(this["ZEITSPANNE_VON"]));
            }
            set {
                this["ZEITSPANNE_VON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ZEITSPANNE_BIS {
            get {
                return ((string)(this["ZEITSPANNE_BIS"]));
            }
            set {
                this["ZEITSPANNE_BIS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CHECKED_ERSTESEKUNDEN {
            get {
                return ((bool)(this["CHECKED_ERSTESEKUNDEN"]));
            }
            set {
                this["CHECKED_ERSTESEKUNDEN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CHECKED_VIDEOFORMAT {
            get {
                return ((bool)(this["CHECKED_VIDEOFORMAT"]));
            }
            set {
                this["CHECKED_VIDEOFORMAT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CHECKED_AUDIO_ONLY {
            get {
                return ((bool)(this["CHECKED_AUDIO_ONLY"]));
            }
            set {
                this["CHECKED_AUDIO_ONLY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CHECKED_ZEITSPANNE {
            get {
                return ((bool)(this["CHECKED_ZEITSPANNE"]));
            }
            set {
                this["CHECKED_ZEITSPANNE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ERSTESEKUNDEN_SEKUNDEN {
            get {
                return ((string)(this["ERSTESEKUNDEN_SEKUNDEN"]));
            }
            set {
                this["ERSTESEKUNDEN_SEKUNDEN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SELECTED_AUDIO_FORMAT {
            get {
                return ((string)(this["SELECTED_AUDIO_FORMAT"]));
            }
            set {
                this["SELECTED_AUDIO_FORMAT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest")]
        public string YTDLP_RELEASE_URL {
            get {
                return ((string)(this["YTDLP_RELEASE_URL"]));
            }
            set {
                this["YTDLP_RELEASE_URL"] = value;
            }
        }
    }
}
